name: pepe_self_ordering_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.2.7
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  mobile_scanner: ^6.0.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/pepe_app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/drawable_xml/
    - assets/fonts/
  fonts:
    - family: Actor
      fonts:
        - asset: assets/fonts/actor_regular.ttf
    - family: CarterOne
      fonts:
        - asset: assets/fonts/carterone_regular.ttf
